### ISSUE TITLE
failed to create deployment

### ISSUE THREAD

**Issue by bodiug** [GoogleCloudPlatform/spinnaker-deploymentmanager#4]
I'm getting an error when trying to create a new spinnaker deployment:

```
guidob@meister:~/git/github/spinnaker-deploymentmanager master ± gcloud --project xxx-sandbox-spinnaker deployment-manager deployments create --config config.jinja spinnaker --properties jenkinsPassword=xxx 
WARNING: Delimiter '=' is deprecated for properties flag. Use ':' instead.
The fingerprint of the deployment is LPqm4PvYwhuJpj5r_rgIkw==
Waiting for create [operation-1490341968661-54b7547a2ca08-f02c391f-cacec7b8]...failed.                                                                                                    
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1490341968661-54b7547a2ca08-f02c391f-cacec7b8]: errors:
- code: RESOURCE_ERROR
  location: /deployments/spinnaker/resources/spinnaker-spinnaker-bucket
  message: '{"ResourceType":"storage.v1.bucket","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"errors":[{"domain":"global","message":"Caller
    does not have storage.buckets.get access to bucket spinnaker-spinnaker-bucket.","reason":"forbidden"}],"message":"Caller
    does not have storage.buckets.get access to bucket spinnaker-spinnaker-bucket.","statusMessage":"Forbidden","requestPath":"https://www.googleapis.com/storage/v1/b/spinnaker-spinnaker-bucket"}}'
```

Is there something I'm missing here?

**Comment by danisla** [comment]
@guidob, in your GCP console, under IAM, make sure your `Google APIs service account` has the following roles, if not add them and try again:

- Compute Instance Admin (v1)
- Compute Network Admin
- Compute Storage Admin
- Storage Admin

From the output, it looks like your deployment name is `spinnaker` so the bucket name it's trying to create is `spinnaker-spinnaker-bucket` which is probably owned by someone else.

Make sure your deployment name is unique because it's [used as part of the bucket name](https://github.com/GoogleCloudPlatform/spinnaker-deploymentmanager/blob/master/templates/spinnaker.jinja#L30). 
For example, try creating the deployment with the name `guidob-spinnaker` and see if that helps.

**Comment by bodiug** [comment]
Thanks @danisla, didn't think about that. Will try that.
